backend:
  name: github
  repo: MustafaGuler98/mustafaguler.me-blog
  base_url: "https://mustafaguler.me/blog/admin/oauth"
  auth_endpoint: "auth.php"   # => tam URL: /blog/admin/oauth/auth.php

site_url: "https://mustafaguler.me"
base_url: "/blog"

media_folder: "public/blog/assets/uploads"
public_folder: "/blog/assets/uploads"

collections:
  - name: "posts"
    label: "Yazılar"
    folder: "src/content/posts/tr"
    create: true
    format: "frontmatter"
    fields:
      - { name: "title", label: "Başlık", widget: "string" }
      - { name: "body",  label: "İçerik", widget: "markdown" }
